
DROP TABLE IF EXISTS `bro_conn`;
CREATE TABLE IF NOT EXISTS `bro_conn` (
  `CONN_ID` bigint(20) unsigned NOT NULL,
  `CONN_TS` timestamp(6) NOT NULL,
  `CONN_UID` char(20) NOT NULL,
  `CONN_ORIGH` varbinary(16) NOT NULL,
  `CONN_ORIGP` smallint(5) unsigned NOT NULL,
  `CONN_RESPH` varbinary(16) NOT NULL,
  `CONN_RESPP` smallint(5) unsigned NOT NULL,
  `CONN_PROTO` char(4) NOT NULL,
  `CONN_SERVICE` char(7) NOT NULL,
  `CONN_DURATION` decimal(11,6) NOT NULL,
  `CONN_ORIGBYTES` int(10) unsigned NOT NULL,
  `CONN_RESPBYTES` int(10) unsigned NOT NULL,
  `CONN_CONNSTATE` char(10) NOT NULL,
  `CONN_HISTORY` char(10) NOT NULL,
  `CONN_ORIGPKTS` int(10) unsigned NOT NULL,
  `CONN_ORIGIPBYTES` int(10) unsigned NOT NULL,
  `CONN_RESPPKTS` int(10) unsigned NOT NULL,
  `CONN_RESPIPBYTES` int(10) unsigned NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `bro_dns`;
CREATE TABLE IF NOT EXISTS `bro_dns` (
  `DNS_ID` bigint(20) unsigned NOT NULL,
  `DNS_UID` char(20) NOT NULL,
  `DNS_TRANSID` char(20) NOT NULL,
  `DNS_QUERY` char(255) NOT NULL,
  `DNS_CLASSNAME` char(255) NOT NULL,
  `DNS_TYPENAME` char(255) NOT NULL,
  `DNS_ANSWERS` char(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `bro_file`;
CREATE TABLE IF NOT EXISTS `bro_file` (
  `FILE_ID` bigint(20) unsigned NOT NULL,
  `FILE_FUID` char(20) NOT NULL,
  `FILE_TXHOST` varbinary(16) NOT NULL,
  `FILE_RXHOST` varbinary(16) NOT NULL,
  `FILE_UID` char(20) NOT NULL,
  `FILE_SOURCE` char(254) NOT NULL,
  `FILE_ANALYZERS` char(50) NOT NULL,
  `FILE_MIME` char(50) NOT NULL,
  `FILE_FILENAME` char(100) NOT NULL,
  `FILE_MD5` char(32) NOT NULL,
  `FILE_SHA1` char(40) NOT NULL,
  `FILE_SHA256` char(64) NOT NULL,
  `FILE_EXTRACTED` char(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `bro_http`;
CREATE TABLE IF NOT EXISTS `bro_http` (
  `HTTP_ID` bigint(20) unsigned NOT NULL,
  `HTTP_UID` char(20) NOT NULL,
  `HTTP_METHOD` char(10) NOT NULL,
  `HTTP_HOST` char(255) NOT NULL,
  `HTTP_URI` char(255) NOT NULL,
  `HTTP_REFERRER` char(255) NOT NULL,
  `HTTP_USERAGENT` char(255) NOT NULL,
  `HTTP_REQLEN` smallint(5) unsigned NOT NULL,
  `HTTP_RESPLEN` smallint(5) unsigned NOT NULL,
  `HTTP_STATUSCODE` smallint(5) unsigned NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `bro_conn`
  ADD PRIMARY KEY (`CONN_ID`),
  ADD KEY `CONN_ORIGH` (`CONN_ORIGH`),
  ADD KEY `CONN_ORIGP` (`CONN_ORIGP`),
  ADD KEY `CONN_RESPH` (`CONN_RESPH`),
  ADD KEY `CONN_RESPP` (`CONN_RESPP`);

ALTER TABLE `bro_dns`
  ADD PRIMARY KEY (`DNS_ID`),
  ADD KEY `DNS_UID` (`DNS_UID`),
  ADD KEY `DNS_QUERY` (`DNS_QUERY`);

ALTER TABLE `bro_file`
  ADD PRIMARY KEY (`FILE_ID`),
  ADD KEY `FILE_FUID` (`FILE_FUID`),
  ADD KEY `FILE_TXHOST` (`FILE_TXHOST`),
  ADD KEY `FILE_RXHOST` (`FILE_RXHOST`),
  ADD KEY `FILE_UID` (`FILE_UID`);

ALTER TABLE `bro_http`
  ADD PRIMARY KEY `HTTP_ID` (`HTTP_ID`);

ALTER TABLE `bro_conn`
  MODIFY `CONN_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT;

ALTER TABLE `bro_dns`
  MODIFY `DNS_ID` bigint(20) NOT NULL AUTO_INCREMENT;
  
ALTER TABLE `bro_file`
  MODIFY `FILE_ID` bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `bro_http`
  MODIFY `HTTP_ID` bigint(20) NOT NULL AUTO_INCREMENT;  
